language: java
jdk: openjdk7
cache:
  directories:
  - $HOME/.m2
script:
 - mvn verify
 - mvn clean compile assembly:single
 - ls -l target/lightning*
after_success:
 - mvn -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean verify jacoco:report coveralls:report