notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bef4eada69f81d1f6a5b
    on_success: always
    on_failure: always
    on_start: always
os:
 - linux
language: java
jdk: openjdk7
cache:
  directories:
   - $HOME/.m2
script:
 - mvn -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID test jacoco:report coveralls:report
 - mvn clean compile assembly:single
 - ./src/test/scripts/console/output/verify_3_0_0.sh
 - ./src/test/scripts/console/output/verify_1_1_1.sh
 - ./src/test/scripts/console/output/report_10_0.sh
 - ./src/test/scripts/exit/code/verify_1_1_1.sh
 - ./src/test/scripts/exit/code/verify_3_0_0.sh
 - ./src/test/scripts/exit/code/report_2_0.sh
 - ./src/test/scripts/exit/code/report_2_1.sh
 - ls -l target/lightning-standalone-*.jar
