notifications:
  email: false
os:
 - linux
 - osx
language: java
cache:
  directories:
   - $HOME/.m2
script:
 - export JAVA_HOME=$(/usr/libexec/java_home) && mvn -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID test jacoco:report coveralls:report
 - export JAVA_HOME=$(/usr/libexec/java_home) && mvn clean compile assembly:single
 - ./src/test/scripts/console/output/verify_3_0_0.sh
 - ./src/test/scripts/console/output/verify_1_1_1.sh
 - ./src/test/scripts/console/output/report_10_0.sh
 - ./src/test/scripts/exit/code/verify_1_1_1.sh
 - ./src/test/scripts/exit/code/verify_3_0_0.sh
 - ./src/test/scripts/exit/code/report_2_0.sh
 - ./src/test/scripts/exit/code/report_2_1.sh
 - ls -l target/lightning-standalone-*.jar
